# Generated by Django 5.2.6 on 2025-09-29 12:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Mensaje de chat', 'verbose_name_plural': 'Mensajes de chat'},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='response',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='bot_response',
            field=models.TextField(blank=True, default='', verbose_name='Respuesta del bot'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Clave de sesión (para usuarios anónimos)'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user_message',
            field=models.TextField(blank=True, default='', verbose_name='Mensaje del usuario'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
