# Generated by Django 5.2.6 on 2025-09-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderproduct_color_remove_orderproduct_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ruc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC'),
        ),
    ]
