# Generated by Django 5.2.6 on 2025-09-30 23:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_ruc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='DavBorn Store', max_length=200)),
                ('ruc', models.CharField(default='6771099-0', max_length=20)),
                ('direccion', models.TextField(default='Km5 Monday Presidente Franco')),
                ('telefono', models.CharField(default='+595 984 538502', max_length=50)),
                ('email', models.EmailField(default='surubi991@gmail.com', max_length=254)),
                ('actividad_economica', models.CharField(default='Comercio de productos electronicos, oficina, gaming, etc', max_length=200)),
            ],
            options={
                'verbose_name': 'Configuración Empresa',
                'verbose_name_plural': 'Configuración Empresa',
            },
        ),
        migrations.CreateModel(
            name='NumeracionFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punto_emision', models.CharField(default='001', max_length=3)),
                ('caja', models.CharField(default='001', max_length=3)),
                ('numero_actual', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Numeración Factura',
                'verbose_name_plural': 'Numeración Facturas',
            },
        ),
        migrations.CreateModel(
            name='Timbrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default='12345678', max_length=8)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Timbrado',
                'verbose_name_plural': 'Timbrados',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='fecha_emision',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='timbrado',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
